[package]
name = "monstrous"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0+"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
bevy_ecs_tilemap = "0.6.0"
